dataset:
  name: "heldout_test"
  label_file: "heldout_test.csv"

model:
  name: "custom" # custom, resnet18, resnet34, resnet50
  num_classes: 1 # 1 - if using binary_crossentropy
  gpu: 0

save_dir: "saved_models"
logs_dir: "logs"