dataset:
  name: "mfcc"

model:
  name: "custom" # custom, resnet18, resnet34, resnet50
  learning_rate: 0.0001
  batch_size: 32
  num_epochs: 100
  num_classes: 1 # 1 - if using binary_crossentropy
  gpu: 0
  optimizer: "adam"
  early_stopping: true
  patience: 10
  loss: "binary_crossentropy" # TODO: Add support more loss functions
  eval_every: 2
  save_every: 2
  oversample: true

save_dir: "saved_models"
logs_dir: "logs"